![title](num.png)

## What is NumPy?
 NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Why use NumPy

![title](arr.png)

<h1 style="color: #4fce42">Let's Get Started ;)</h1>

#### Importing the library:

In [1]:
import numpy as np

#### Why use numpy:

In [2]:
# Numpy Arrays
array_1d=np.array([1,2,3])
array_2d=np.array([[1,2,3],[4,5,6]])
print("1D Array:\n",array_1d)
print("2D Array:\n",array_2d)

1D Array:
 [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
#Comparing ndarrays with lists
list1=[1,2,3]
list2=[1,1,1]
list4=[]
list3=list1+list2
## Adding two lists would give us the following result
print("Appending Two Lists:",list3)
for i in range(0,len(list1)):
    list4.append(list1[i]+list2[i])
print("Adding Two Lists:",list4)

Appending Two Lists: [1, 2, 3, 1, 1, 1]
Adding Two Lists: [2, 3, 4]


In [4]:
## Adding two nd arrays:
a=np.array([1,2,3])
b=np.array([1,1,1])
c=np.array(a+b)
print(c)

[2 3 4]


In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.random.randint(1,10,(2,3))

array([[5, 3, 1],
       [1, 9, 8]])

In [8]:
np.random.randn(3,4)

array([[-0.56651073, -1.89728303, -0.09499794,  3.69874877],
       [-0.4802047 ,  0.78381443,  1.39435862, -0.21302662],
       [-1.44556962, -0.25480073, -0.70045268,  1.89823942]])

In [9]:
np.random.rand(3,4)

array([[0.1056097 , 0.2701586 , 0.9597843 , 0.77623892],
       [0.46544432, 0.20797276, 0.55493125, 0.03708217],
       [0.62677602, 0.18880353, 0.91465838, 0.8401961 ]])

In [10]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [11]:
np.empty((3,3))

array([[-2.31584178e+077, -1.73059869e-077,  4.44659081e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [12]:
## Size,Shape and Dimension of an array
size_a=np.size(array_1d)
size_b=np.size(array_2d)
shape_a=np.shape(array_1d)
shape_b=np.shape(array_2d)
dim_a=np.ndim(array_1d)
dim_b=np.ndim(array_2d)
print("size_a:",size_a,"\nsize_b",size_b)
print("shape_a:",shape_a,"\nshape_b",shape_b)
print("Dimension of a:",dim_a)
print("Dimension of b:",dim_b)

size_a: 3 
size_b 6
shape_a: (3,) 
shape_b (2, 3)
Dimension of a: 1
Dimension of b: 2


In [13]:
##Indexing and slicing
### Indexing
print(array_1d[2])
###slicing
print(array_2d[:,0:3])
print(array_2d[:,2])
print(array_2d[:,-1])

3
[[1 2 3]
 [4 5 6]]
[3 6]
[3 6]


In [14]:
###Fancy Indexing
f=[[1],[2]]
print(array_2d[f])
s=[[0,1],[1]]
array_2d[s]

[6]


array([2, 5])

<h2 style="color:#87053d">Comparing Two arrays</h2>

In [30]:
ax=np.array([1,2,3,4])
ay=np.array([1,2,3,4])
ax==ay

array([ True,  True,  True,  True])

In [31]:
ax!=ay

array([False, False, False, False])

In [32]:
ax>ay

array([False, False, False, False])

In [33]:
ax>3

array([False, False, False,  True])

In [34]:
ax>=3

array([False, False,  True,  True])

<h2 style="color:#6c0de0">Arthimetic Operations</h2>

In [40]:
print(ax+ay)
np.add(ax,ay)

[2 4 6 8]


array([2, 4, 6, 8])

In [41]:
print(ax-ay)
np.subtract(ax,ay)

[0 0 0 0]


array([0, 0, 0, 0])

In [42]:
print(ax*ay)
np.multiply(ax,ay)

[ 1  4  9 16]


array([ 1,  4,  9, 16])

In [44]:
bx=np.array([[1,2,3],[1,2,1]])
by=np.array([[1,2],[3,4],[5,6]])
bx.dot(by)

array([[22, 28],
       [12, 16]])

<h2 style="color:#f4b342">Universal Functions in Numpy:</h2>

In [15]:
x=np.random.randint(1,100,(3,3))
x

array([[67, 91, 75],
       [58, 21,  7],
       [84, 56, 40]])

In [16]:
np.max(x)

91

In [17]:
np.sum(x)

499

In [18]:
np.mean(x)

55.44444444444444

In [19]:
np.sqrt(x)

array([[8.18535277, 9.53939201, 8.66025404],
       [7.61577311, 4.58257569, 2.64575131],
       [9.16515139, 7.48331477, 6.32455532]])

In [20]:
np.std(x)

26.61290877713759

In [21]:
np.power(x,2)

array([[4489, 8281, 5625],
       [3364,  441,   49],
       [7056, 3136, 1600]])

In [22]:
print("sine values:",np.sin(x))
print("Cosine values:",np.cos(x))

sine values: [[-0.85551998  0.10598751 -0.38778164]
 [ 0.99287265  0.83665564  0.6569866 ]
 [ 0.73319032 -0.521551    0.74511316]]
Cosine values: [[-0.5177698  -0.99436746  0.92175127]
 [ 0.11918014 -0.54772926  0.75390225]
 [-0.6800235   0.85322011 -0.66693806]]


In [23]:
x.sort(axis=0)
x

array([[58, 21,  7],
       [67, 56, 40],
       [84, 91, 75]])

In [24]:
y=np.random.randint(1,20,(3,4))
y.shape

(3, 4)

In [25]:
## Matrix transpose
y=y.transpose()
y.shape

(4, 3)

In [26]:
##Resizing the array
z=np.random.randint(1,20,9)
z.shape

(9,)

In [27]:
z.reshape(3,3)

array([[ 6,  4,  3],
       [14, 14, 10],
       [14,  1, 11]])

<h2 style="color: #e84f29">Saving and Loading files</h2>

In [28]:
np.save('my_array.npz',x)

In [29]:
x_saved=np.load('my_array.npz.npy')
x_saved

array([[58, 21,  7],
       [67, 56, 40],
       [84, 91, 75]])